name: Database Migration

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Perform a dry run without actually migrating data"
        required: true
        type: boolean
        default: true

env:
  SUPABASE_DB_HOST: ${{ secrets.SUPABASE_DB_HOST }}
  SUPABASE_DB_NAME: ${{ secrets.SUPABASE_DB_NAME }}
  SUPABASE_DB_USER: ${{ secrets.SUPABASE_DB_USER }}
  SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
  AZURE_DB_HOST: ${{ secrets.AZURE_DB_HOST }}
  AZURE_DB_NAME: ${{ secrets.AZURE_DB_NAME }}
  AZURE_DB_USER: ${{ secrets.AZURE_DB_USER }}
  AZURE_DB_PASSWORD: ${{ secrets.AZURE_DB_PASSWORD }}

jobs:
  migrate:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Create backup directory
        run: mkdir -p ./backup

      - name: Dump Supabase database
        run: |
          PGPASSWORD=$SUPABASE_DB_PASSWORD pg_dump \
            -h $SUPABASE_DB_HOST \
            -U $SUPABASE_DB_USER \
            -d $SUPABASE_DB_NAME \
            -F c \
            -b \
            -v \
            --exclude-table-data=public.events \
            -f ./backup/supabase_backup_$(date +%Y%m%d_%H%M%S).dump

      - name: Verify dump file
        run: |
          if [ ! -s ./backup/supabase_backup_*.dump ]; then
            echo "Error: Dump file is empty or does not exist"
            exit 1
          fi
          echo "Dump file size: $(du -h ./backup/supabase_backup_*.dump | cut -f1)"

      - name: Restore to Azure (if not dry run)
        if: ${{ github.event.inputs.dry_run == 'false' }}
        run: |
          # Drop all tables in public schema
          PGPASSWORD=$AZURE_DB_PASSWORD psql \
            -h $AZURE_DB_HOST \
            -U $AZURE_DB_USER \
            -d $AZURE_DB_NAME \
            -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;" || exit 1

          # Restore the table
          PGPASSWORD=$AZURE_DB_PASSWORD pg_restore \
            -h $AZURE_DB_HOST \
            -U $AZURE_DB_USER \
            -d $AZURE_DB_NAME \
            --clean \
            --if-exists \
            --no-owner \
            --disable-triggers \
            -v \
            ./backup/supabase_backup_*.dump || exit 1

      - name: Verify Azure database (if not dry run)
        if: ${{ github.event.inputs.dry_run == 'false' }}
        run: |
          PGPASSWORD=$AZURE_DB_PASSWORD psql \
            -h $AZURE_DB_HOST \
            -U $AZURE_DB_USER \
            -d $AZURE_DB_NAME \
            -c "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public';" || exit 1

      - name: Cleanup
        if: always()
        run: rm -rf ./backup
